#!/usr/bin/env node

/****************************************************************************
 The MIT License (MIT)
 Copyright (c) 2015 Apigee Corporation
 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:
 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.
 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 ****************************************************************************/

'use strict';

const { version: edgemicroVersion, engines } = require('../package.json');
const writeConsoleLog = require('../core').Logging.writeConsoleLog;
const semver = require('semver');

const nodeVersion = process.version;
const majorVersion = parseInt(nodeVersion.slice(1).split('.')[0], 10);
const CONSOLE_LOG_TAG_COMP = 'microgateway edgemicro';

// Add the --no-deprecation flag to NODE_OPTIONS
process.env.NODE_OPTIONS = (process.env.NODE_OPTIONS || '') + ' --no-deprecation';

// Don't print versions when obtaining a token.
if (!process.argv.includes('token') && !process.argv.includes('get')) {
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'current nodejs version is %s', nodeVersion);
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'current edgemicro version is %s', edgemicroVersion);
}

// Warn if using odd-numbered Node (non-LTS, short-lived)
if (majorVersion % 2 !== 0) {
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'You are using a version of NodeJS that is not supported');
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'Supported Node.js versions : %s', engines.node);
    process.exit(1);
}

// Warn if running on an LTS version that’s near end-of-support
// (Here we check if the lowest allowed version is the current major)
const minSupportedMajor = semver.minVersion(engines.node)?.major;
if (majorVersion === minSupportedMajor) {
    writeConsoleLog(
        'log',
        { component: CONSOLE_LOG_TAG_COMP },
        '\x1b[33m%s\x1b[0m',
        `Current Node.js version is ${nodeVersion}. Note, v${majorVersion}.x.x will be out of support soon, see https://docs.apigee.com/release/notes/edge-microgateway-release-notes-0`
    );
}

// Runtime enforcement of package.json engines.node
if (!semver.satisfies(nodeVersion, engines.node, { includePrerelease: true })) {
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'You are using a version of NodeJS that is not supported');
    writeConsoleLog('log', { component: CONSOLE_LOG_TAG_COMP }, 'Supported Node.js versions : %s', engines.node);
    process.exit(1);
}

// Load and run the CLI command handler
require('./cmd')();